/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicianRouteImport } from './routes/academician'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as RecruiterRouteImport } from './routes/recruiter'
import { Route as StudentRouteImport } from './routes/student'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicianRoute = AcademicianRouteImport.update({
  id: '/academician',
  path: '/academician',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRoute = RecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academician': typeof AcademicianRoute
  '/mentor': typeof MentorRoute
  '/recruiter': typeof RecruiterRoute
  '/student': typeof StudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academician': typeof AcademicianRoute
  '/mentor': typeof MentorRoute
  '/recruiter': typeof RecruiterRoute
  '/student': typeof StudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academician': typeof AcademicianRoute
  '/mentor': typeof MentorRoute
  '/recruiter': typeof RecruiterRoute
  '/student': typeof StudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/academician' | '/mentor' | '/recruiter' | '/student'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/academician' | '/mentor' | '/recruiter' | '/student'
  id: '__root__' | '/' | '/academician' | '/mentor' | '/recruiter' | '/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicianRoute: typeof AcademicianRoute
  MentorRoute: typeof MentorRoute
  RecruiterRoute: typeof RecruiterRoute
  StudentRoute: typeof StudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academician': {
      id: '/academician'
      path: '/academician'
      fullPath: '/academician'
      preLoaderRoute: typeof AcademicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicianRoute: AcademicianRoute,
  MentorRoute: MentorRoute,
  RecruiterRoute: RecruiterRoute,
  StudentRoute: StudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
